# Generated by Django 4.1.7 on 2023-05-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('studentid', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
